name: artsaxis
favicon: null
layout_spectrum: 0.75157
typography_spectrum: 0.25569
title: arts axis llc
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#947e71'
    - '#3a322f'
    - '#febb4c'
    - '#b25100'
    - '#fce6d8'
  brandStrength: 0.8246840913780034
  lightness: 0.5625
  saturation: 0.7368409894406796
  rhythmicContrast: 0.75
purpose: []
